image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  build
  test
  deploy

build-job:
  stage: build
  script:
    - 'dotnet build'

test-job:
  stage: test
  script:
    - echo "TODO: Run tests"

deploy-job:
  stage: deploy
  only:
    - main
  artifacts:
    paths:
      - publish/
  script:
    - 'dotnet publish -c Release -o ../publish Bilbo/Bilbo.csproj'